const fs = require('fs');

const questions = [];
let idCounter = 10000;

const topics = [
  "Design Twitter",
  "Design YouTube",
  "Design Netflix",
  "Design Uber",
  "Design WhatsApp",
  "Design Instagram",
  "Design TikTok",
  "Design Google Maps",
  "Design Google Search",
  "Design Airbnb",
  "Design Amazon",
  "Design Slack",
  "Design Zoom",
  "Design a URL Shortener",
  "Design a Web Crawler",
  "Design a Rate Limiter",
  "Design a Key-Value Store",
  "Design a Notification System",
  "Design an APM (Datadog)",
  "Design a Distributed Cache",
  "Design a Distributed Message Queue",
  "Design a Distributed Task Scheduler",
  "Design a Search Auto-complete",
  "Design a News Feed System",
  "Design a Leaderboard",
  "Design a Recommendation System",
  "Design a Parking Lot System",
  "Design a Vending Machine",
  "Design an Elevator System",
  "Design a Chess Game",
  "Design a Logging System",
  "Design a Proximity Service (Yelp)",
  "Design a Distributed Lock",
  "Design a CDN",
  "Design a Video Streaming Platform",
  "Design a Payment Gateway",
  "Design a Stock Exchange",
  "Design a Trading System",
  "Design a Banking System",
  "Design a Ticket Booking System (BookMyShow)",
  "Design an E-commerce Cart",
  "Design a Hotel Booking System",
  "Design a Flight Booking System",
  "Design a Ride-Sharing App",
  "Design a Food Delivery App",
  "Design a Chat Application",
  "Design a Document Editor (Google Docs)",
  "Design a Code Deployment System",
  "Design a CI/CD Pipeline",
  "Design an API Gateway",
  "Design a Load Balancer",
  "Design a DNS Server",
  "Design a Database Management System",
  "Design a Backup System",
  "Design a Fraud Detection System",
  "Design a Data Warehouse",
  "Design a Metrics System",
  "Design an Alerting System",
  "Design a Configuration Management System",
  "Design a Recommendation Engine",
  "Design an Analytics System",
  "Design a Web Browser",
  "Design an Operating System Module",
  "Design a Virtual Machine",
  "Design a Cloud Infrastructure",
  "Design a Container Orchestrator",
  "Design a Serverless Platform",
  "Design a Graph Database",
  "Design a Document Database",
  "Design a Time Series Database",
  "Design a Microservice Architecture",
  "Design a Service Mesh",
  "Design a Identity Provider (OAuth)",
  "Design a Two-Factor Authentication System",
  "Design a Captcha System",
  "Design a Web Application Firewall",
  "Design a Penetration Testing Tool",
  "Design a Vulnerability Scanner",
  "Design a Malware Detection System",
  "Design an Intrusion Detection System",
  "Design a Data Loss Prevention System",
  "Design a Password Manager",
  "Design a Key Management Service",
  "Design a Cryptographic Library",
  "Design a Smart Contract",
  "Design a Blockchain",
  "Design a Crypto Exchange",
  "Design a Web3 Application",
  "Design an IoT Platform",
  "Design an Edge Computing System",
  "Design a Machine Learning Pipeline",
  "Design a Data Processing System (Spark)",
  "Design a Stream Processing System (Flink)",
  "Design a MapReduce Framework",
  "Design a Data Lake",
  "Design an ETL Tool",
  "Design a Data Integration Platform",
  "Design a Business Intelligence Dashboard",
  "Design an Advertisement Click Prediction System",
  "Design a Distributed File System like HDFS",
  "Design a Cloud Storage System (S3)",
  "Design a Live Video Broadcasting System",
  "Design a Collaborative Whiteboard",
  "Design an Online Multiplayer Game Backend"
];

topics.forEach(topic => {
  questions.push({
    id: idCounter++,
    category: 'System Design',
    question: topic,
    answer: "Detailed scenario and walk-through covering: 1. Requirements (Functional & Non-Functional), 2. Capacity Estimation, 3. High Level Design, 4. Component Details, 5. API Design, 6. Data Model, 7. Scaling (Load balancing, Caching, Sharding), 8. Fault Tolerance & Bottlenecks.",
    isPlatform: false,
    tags: ["System Design", "Architecture"]
  });
});

fs.writeFileSync('src/systemDesignData.ts', `export const systemDesignQuestions = ${JSON.stringify(questions, null, 2)};`);
